name: random-choice-check
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: run random choice
        run: |
          python main.py
